services:
  - type: web
    name: appcompilerai
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: "python3 server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: HOST
        value: 0.0.0.0
